/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formuariosmdi;

import javax.swing.JOptionPane;

/**
 *
 * @author willi
 */
public class Frmprincipal extends javax.swing.JFrame {

    /**
     * Creates new form Frmprincipal
     */
    public Frmprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opsuma = new javax.swing.JMenuItem();
        opresta = new javax.swing.JMenuItem();
        opdivision = new javax.swing.JMenuItem();
        opmultiplicacion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        saterminar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        jMenu1.setText("Operaciones");

        opsuma.setText("Suma");
        opsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opsumaActionPerformed(evt);
            }
        });
        jMenu1.add(opsuma);

        opresta.setText("Resta");
        opresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oprestaActionPerformed(evt);
            }
        });
        jMenu1.add(opresta);

        opdivision.setText("División");
        opdivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opdivisionActionPerformed(evt);
            }
        });
        jMenu1.add(opdivision);

        opmultiplicacion.setText("Multiplicación");
        opmultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opmultiplicacionActionPerformed(evt);
            }
        });
        jMenu1.add(opmultiplicacion);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        saterminar.setText("Terminar");
        saterminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saterminarActionPerformed(evt);
            }
        });
        jMenu2.add(saterminar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opsumaActionPerformed
        // TODO add your handling code here:
        Frmsuma frmsuma= new Frmsuma();
        frmsuma.setVisible(true);
        jDesktopPane1.add(frmsuma);
    }//GEN-LAST:event_opsumaActionPerformed

    private void oprestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oprestaActionPerformed
        // TODO add your handling code here:
        Frmresta frmresta= new Frmresta();
        frmresta.setVisible(true);
        jDesktopPane1.add(frmresta);
    }//GEN-LAST:event_oprestaActionPerformed

    private void opdivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opdivisionActionPerformed
        // TODO add your handling code here:
        Frmdivision frmdivision=new Frmdivision();
        frmdivision.setVisible(true);
        jDesktopPane1.add(frmdivision);
    }//GEN-LAST:event_opdivisionActionPerformed

    private void opmultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opmultiplicacionActionPerformed
        // TODO add your handling code here:
        Frmmultiplicacion frmmultiplicacion=new Frmmultiplicacion();
        frmmultiplicacion.setVisible(true);
        jDesktopPane1.add(frmmultiplicacion);
    }//GEN-LAST:event_opmultiplicacionActionPerformed

    private void saterminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saterminarActionPerformed
        // TODO add your handling code here:
        String botones[]={"Salir","Cancelar"};
        int respuesta= JOptionPane.showOptionDialog(this,"Deseas salir?","Confirmacion",0,0,null,botones,this);
        if (respuesta==JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_saterminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem opdivision;
    private javax.swing.JMenuItem opmultiplicacion;
    private javax.swing.JMenuItem opresta;
    private javax.swing.JMenuItem opsuma;
    private javax.swing.JMenuItem saterminar;
    // End of variables declaration//GEN-END:variables
}
